<script src="/js/libs/jquery-1.10.2-min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/jquery.cookie.js"></script>
<script src="/js/libs/simplecart/simpleCart.js"></script>
<script src="/js/cart.js"></script>
<script src="/js/tracking.js"></script>
<script src="/js/collapsible.js"></script>
<script src="/js/lazyload.min.js"></script>
<script src="/js/google-analytics.js"></script>
<script>document.write('<script src="http://' + (location.host || 'localhost')
.split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>