<? // count = 63

$inventory  = array(

	array(
		"id" => "4",
		"line" => "stz",
		"title" => "Right Coast",
		"basePrice" => "$20",
		"big_image" => "stz/rightcoast.red.main.png",
		"paypal_code" => "28SZB2QH6QWAU",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/rightcoast.red.more.png",
		"product_image" => "stz/rightcoast.red.products.png",
		"shirt_color" => "Heather Red",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "21",
		"line" => "stz",
		"title" => "Right Coast",
		"basePrice" => "$20",
		"big_image" => "stz/rightcoast.heatherblue.main.png",
		"paypal_code" => "D3YCL4X52UDP8",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/rightcoast.heatherblue.more.png",
		"product_image" => "stz/rightcoast.heatherblue.products.png",
		"shirt_color" => "Heather Blue",
		"ink_color" => "Black",
	),

	array(
		"id" => "22",
		"line" => "stz",
		"title" => "Right Coast",
		"basePrice" => "$20",
		"big_image" => "stz/rightcoast.heathergrey.main.png",
		"paypal_code" => "VKWZGMVLNL5SQ",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/rightcoast.heathergrey.more.png",
		"product_image" => "stz/rightcoast.heathergrey.products.png",
		"shirt_color" => "Heather Grey",
		"ink_color" => "Black",
	),

	array(
		"id" => "0",
		"line" => "stz",
		"title" => "El Caputo",
		"basePrice" => "$20",
		"big_image" => "stz/elcaputo.red.main.png",
		"paypal_code" => "LG35VXV47A9R4",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/elcaputo.red.more.png",
		"product_image" => "stz/elcaputo.red.products.png",
		"shirt_color" => "Heather Red",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "2",
		"line" => "stz",
		"title" => "Happy Shredding",
		"basePrice" => "$20",
		"big_image" => "stz/happyshredding.main.png",
		"paypal_code" => "F47CK5SMA8ABY",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/happyshredding.more.png",
		"product_image" => "stz/happyshredding.products.png",
		"shirt_color" => "Maroon",
		"ink_color" => "Orange",
	),
	
	array(
		"id" => "6",
		"line" => "stz",
		"title" => "Ride",
		"basePrice" => "$20",
		"big_image" => "stz/ride.main.png",
		"paypal_code" => "9DRCCU8PJDLHE",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/ride.more.png",
		"product_image" => "stz/ride.products.png",
		"shirt_color" => "Heather Charcoal",
		"ink_color" => "Orange",
	),
	
	array(
		"id" => "7",
		"line" => "stz",
		"title" => "Ride",
		"basePrice" => "$20",
		"big_image" => "stz/ridenc.heathergrey.main.png",
		"paypal_code" => "HLUN9A6SKBPE8",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/ridenc.heathergrey.more.png",
		"product_image" => "stz/ridenc.heathergrey.products.png",
		"shirt_color" => "Heather Grey",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "33",
		"line" => "stz",
		"title" => "Emergency Mustache",
		"basePrice" => "$20",
		"big_image" => "stz/emergencymustache.latte.main.png",
		"paypal_code" => "JAZ59VWRCZ8TQ",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/emergencymustache.latte.more.png",
		"product_image" => "stz/emergencymustache.latte.products.png",
		"shirt_color" => "Latte",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "10",
		"line" => "stz",
		"title" => "Skyline",
		"basePrice" => "$20",
		"big_image" => "stz/skyline.white.main.png",
		"paypal_code" => "6PKVME6MBUFXJ",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/skyline.white.more.png",
		"product_image" => "stz/skyline.white.products.png",
		"shirt_color" => "White",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "11",
		"line" => "stz",
		"title" => "Skyline",
		"basePrice" => "$20",
		"big_image" => "stz/skyline.blue.main.png",
		"paypal_code" => "VYB873X523WHN",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/skyline.blue.more.png",
		"product_image" => "stz/skyline.blue.products.png",
		"shirt_color" => "Heather Blue",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "8",
		"line" => "stz",
		"title" => "Shred Til You're Dead",
		"basePrice" => "$20",
		"big_image" => "stz/shredtilyouredead.heathergrey.main.png",
		"paypal_code" => "SGLXLVBLXK99W",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "designed by Josh Varnum",
		"thumbs" => array(
		),
		"more_thumb" => "stz/shredtilyouredead.heathergrey.more.png",
		"product_image" => "stz/shredtilyouredead.heathergrey.products.png",
		"shirt_color" => "Heather Grey",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "9",
		"line" => "stz",
		"title" => "Shred Til You're Dead",
		"basePrice" => "$20",
		"big_image" => "stz/shredtilyouredead.fatigue.main.png",
		"paypal_code" => "ANVPFAGUY2ZR2",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "designed by Josh Varnum",
		"thumbs" => array(
		),
		"more_thumb" => "stz/shredtilyouredead.fatigue.more.png",
		"product_image" => "stz/shredtilyouredead.fatigue.products.png",
		"shirt_color" => "Fatigue",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "12",
		"line" => "stz",
		"title" => "Triangles",
		"basePrice" => "$20",
		"big_image" => "stz/triangles.main.png",
		"paypal_code" => "7VNN6CXRMYD44",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/triangles.more.png",
		"product_image" => "stz/triangles.products.png",
		"shirt_color" => "Heather Red",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "26",
		"line" => "stz",
		"title" => "We Can Do It",
		"basePrice" => "$20",
		"big_image" => "stz/wecandoit.white.main.png",
		"paypal_code" => "62BXCSV5A6UYW",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "designed by Logan Huck",
		"thumbs" => array(
		),
		"more_thumb" => "stz/wecandoit.white.more.png",
		"product_image" => "stz/wecandoit.white.products.png",
		"shirt_color" => "White",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "25",
		"line" => "stz",
		"title" => "We Can Do It",
		"basePrice" => "$20",
		"big_image" => "stz/wecandoit.fatigue.main.png",
		"paypal_code" => "3PMDW588V62NA",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "designed by Logan Huck",
		"thumbs" => array(
		),
		"more_thumb" => "stz/wecandoit.fatigue.more.png",
		"product_image" => "stz/wecandoit.fatigue.products.png",
		"shirt_color" => "Fatigue",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "17",
		"line" => "stz",
		"title" => "OG Whaler",
		"basePrice" => "$20",
		"big_image" => "stz/ogwhaler.white.main.png",
		"paypal_code" => "N6WG9UF3E4M5E",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/ogwhaler.white.more.png",
		"product_image" => "stz/ogwhaler.white.products.png",
		"shirt_color" => "White",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "16",
		"line" => "stz",
		"title" => "OG Whaler",
		"basePrice" => "$20",
		"big_image" => "stz/ogwhaler.heatherblue.main.png",
		"paypal_code" => "RA58L3VUS5Z7Q",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/ogwhaler.heatherblue.more.png",
		"product_image" => "stz/ogwhaler.heatherblue.products.png",	
		"shirt_color" => "Heather Blue",
		"ink_color" => "White",
	),
	
	array(
		"id" => "18",
		"line" => "stz",
		"title" => "Party Animals",
		"basePrice" => "$20",
		"big_image" => "stz/partyanimals.heathercharc.main.png",
		"paypal_code" => "K9QQC3BTAT87J",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/partyanimals.heathercharc.more.png",
		"product_image" => "stz/partyanimals.heathercharc.products.png",
		"shirt_color" => "Heather Charcoal",
		"ink_color" => "Grey",
	),
	
	array(
		"id" => "15",
		"line" => "stz",
		"title" => "Moostache",
		"basePrice" => "$20",
		"big_image" => "stz/moostache.white.main.png",
		"paypal_code" => "GQL8D4P7AH782",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/moostache.white.more.png",
		"product_image" => "stz/moostache.white.products.png",	
		"shirt_color" => "White",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "13",
		"line" => "stz",
		"title" => "Daps N Pounds",
		"basePrice" => "$20",		
		"big_image" => "stz/dapsnpounds.heathercharc.main.png",
		"paypal_code" => "ZRAJP4TG4QVMU",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/dapsnpounds.heathercharc.more.png",
		"product_image" => "stz/dapsnpounds.heathercharc.products.png",
		"shirt_color" => "Heather Charcoal",
		"ink_color" => "Grey",
	),
	
	array(
		"id" => "19",
		"line" => "stz",
		"title" => "Peace",
		"basePrice" => "$20",
		"big_image" => "stz/peace.charcoal.main.png",
		"paypal_code" => "JY36KM7SDLJN8",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/peace.charcoal.more.png",
		"product_image" => "stz/peace.charcoal.products.png",
		"shirt_color" => "Heather Charcoal",
		"ink_color" => "Blue",
	),
	
	array(
		"id" => "14",
		"line" => "stz",
		"title" => "En Garde",
		"basePrice" => "$20",
		"big_image" => "stz/engarde.main.png",
		"paypal_code" => "6ES6YDVNT8CNN",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/engarde.more.png",
		"product_image" => "stz/engarde.products.png",
		"shirt_color" => "White",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "27",
		"line" => "stz",
		"title" => "Shoot All Shred",
		"basePrice" => "$20",
		"big_image" => "stz/shootallshred.white.main.png",
		"paypal_code" => "JFJXVXNHWKJ3G",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/shootallshred.white.more.png",
		"product_image" => "stz/shootallshred.white.products.png",
		"shirt_color" => "White",
		"ink_color" => "Black",
	),	
	
	array(
		"id" => "28",
		"line" => "stz",
		"title" => "I Skate NC",
		"basePrice" => "$20",
		"big_image" => "stz/iskatenc.grey.main.png",
		"paypal_code" => "RJGV3VK4V3SVU",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "designed by Nicky Lovejoy",
		"thumbs" => array(
		),
		"more_thumb" => "stz/iskatenc.grey.more.png",
		"product_image" => "stz/iskatenc.grey.products.png",
		"shirt_color" => "Heather Grey",
		"ink_color" => "Blue",
	),
	
	array(
		"id" => "29",
		"line" => "stz",
		"title" => "Slush Buddie",
		"basePrice" => "$20",
		"big_image" => "stz/slushbuddie.heatherblue.main.png",
		"paypal_code" => "SZVM9BPH5YYV2",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/slushbuddie.heatherblue.more.png",
		"product_image" => "stz/slushbuddie.heatherblue.products.png",
		"shirt_color" => "Heather Blue",
		"ink_color" => "White",
	),
	
	array(
		"id" => "31",
		"line" => "stz",
		"title" => "Too Fresh",
		"basePrice" => "$20",
		"big_image" => "stz/toofresh.white.main.png",
		"paypal_code" => "JHS2PUNF7YS7N",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/toofresh.white.more.png",
		"product_image" => "stz/toofresh.white.products.png",
		"shirt_color" => "White",
		"ink_color" => "Blue",
	),
	
	/*
	array(
		"id" => "3",
		"line" => "stz",
		"title" => "Happy Shredding",
		"basePrice" => "$20",
		"big_image" => "stz/happyshreddingblue.main.png",
		"paypal_code" => "D32J8E877XNG6",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/happyshreddingblue.more.png",
		"product_image" => "stz/happyshreddingblue.products.png",
		"shirt_color" => "Heather Blue",
		"ink_color" => "Black",
	),
	*//*

	array(
		"id" => "23",
		"line" => "stz",
		"title" => "El Caputo",
		"basePrice" => "$20",
		"big_image" => "stz/elcaputofatigue.main.png",
		"paypal_code" => "9DKSUQPYKWAGG",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/elcaputofatigue.more.png",
		"product_image" => "stz/elcaputofatigue.product.png",
		"shirt_color" => "Fatigue",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "24",
		"line" => "stz",
		"title" => "El Caputo",
		"basePrice" => "$20",
		"big_image" => "stz/elcaputolatte.main.png",
		"paypal_code" => "NZQCQPGUS8QUS",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/elcaputolatte.more.png",
		"product_image" => "stz/elcaputolatte.product.png",
		"shirt_color" => "Latte",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "34",
		"line" => "stz",
		"title" => "Hand Shredded",
		"basePrice" => "$20",
		"big_image" => "stz/handshreddedwhite.main.png",
		"paypal_code" => "S3J3TJB7GBSMJ",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/handshreddedwhite.more.png",
		"product_image" => "stz/handshreddedwhite.products.png",
		"shirt_color" => "White",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "35",
		"line" => "stz",
		"title" => "Hand Shredded",
		"basePrice" => "$20",
		"big_image" => "stz/handshreddedblue.main.png",
		"paypal_code" => "HD6AEDTU4RQGE",
		"small_description" => "All graphics are printed on a 4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/handshreddedblue.more.png",
		"product_image" => "stz/handshreddedblue.products.png",
		"shirt_color" => "Heather Blue",
		"ink_color" => "Black",
	),
	*/
	
/*********** Pocket Inventory **********/	
	
	array(
		"id" => "36",
		"line" => "pocket",
		"title" => "'Merica",
		"basePrice" => "$25",
		"big_image" => "pocket/merica.main.png",
		"paypal_code" => "TKX8JDFXSCDGG",
		"small_description" => "4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "pocket/merica.more.png",
		"product_image" => "pocket/merica.products.png",
	),
		
	array(
		"id" => "37",
		"line" => "pocket",
		"title" => "US Mint",
		"basePrice" => "$25",
		"big_image" => "pocket/mint.main.png",
		"paypal_code" => "A522YRRMT5U7E",
		"small_description" => "4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "pocket/mint.more.png",
		"product_image" => "pocket/mint.products.png",
	),
	/*
	array(
		"id" => "38",
		"line" => "pocket",
		"title" => "Bikes",
		"basePrice" => "$20",
		"big_image" => "stz/bikes.main.png",
		"paypal_code" => "YWSZPEV5K4NZN",
		"small_description" => "4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "stz/bikes.more.png",
		"product_image" => "stz/bikes.product.png",
	),
	*/
	array(
		"id" => "39",
		"line" => "pocket",
		"title" => "Thatch",
		"basePrice" => "$25",
		"big_image" => "pocket/thatched.main.png",
		"paypal_code" => "M6BB5CL2FXJUL",
		"small_description" => "4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "pocket/thatched.more.png",
		"product_image" => "pocket/thatched.products.png",
	),
	
	array(
		"id" => "40",
		"line" => "pocket",
		"title" => "Flamingo-ed",
		"basePrice" => "$25",
		"big_image" => "pocket/flamingo.main.png",
		"paypal_code" => "S4NW3X9ZUXPMA",
		"small_description" => "4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "pocket/flamingo.more.png",
		"product_image" => "pocket/flamingo.products.png",
	),
	
	array(
		"id" => "41",
		"line" => "pocket",
		"title" => "G-fruit",
		"basePrice" => "$25",
		"big_image" => "pocket/grapefruit.main.png",
		"paypal_code" => "JFGJTAFLC8PKE",
		"small_description" => "4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "pocket/grapefruit.more.png",
		"product_image" => "pocket/grapefruit.products.png",
	),
	
	array(
		"id" => "42",
		"line" => "pocket",
		"title" => "Polar Bear Club",
		"basePrice" => "$25",
		"big_image" => "pocket/polarbear.main.png",
		"paypal_code" => "YJJNNECW3HBKS",
		"small_description" => "4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "pocket/polarbear.more.png",
		"product_image" => "pocket/polarbear.products.png",
	),
	
	array(
		"id" => "61",
		"line" => "pocket",
		"title" => "Nerd",
		"basePrice" => "$25",
		"big_image" => "pocket/nerd.main.png",
		"paypal_code" => "YWSZPEV5K4NZN",
		"small_description" => "4.3 ounce, 100% ring-spun cotton, longer than average, fitted tee.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "pocket/nerd.more.png",
		"product_image" => "pocket/nerd.products.png",
	),
	
/********** Outer STZ **********/	

	array(
		"id" => "72",
		"line" => "outer",
		"title" => "Custom Hoodie",
		"basePrice" => "$85",
		"big_image" => "outer/customhoodies.main.png",
		"paypal_code" => "4EAA7LXMJCU38",
		"small_description" => "",
		"description" => "Details on the way- check back soon.",
		"thumbs" => array(
		),
		"more_thumb" => "outer/customhoodies.more.png",
		"product_image" => "outer/customhoodies.products.png",
		"shirt_color" => "Custom",
		"ink_color" => "Custom",
	),

	array(
		"id" => "64",
		"line" => "outer",
		"title" => "STZ Life",
		"basePrice" => "$40",
		"big_image" => "outer/stzlifecrew.red.main.gif",
		"paypal_code" => "4EAA7LXMJCU38",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "outer/stzlifecrew.red.more.gif",
		"product_image" => "outer/stzlifecrew.red.products.gif",
		"shirt_color" => "Red",
		"ink_color" => "White",
	),
	
	array(
		"id" => "65",
		"line" => "outer",
		"title" => "STZ Life",
		"basePrice" => "$45",
		"big_image" => "outer/stzlifehoodie.black.main.gif",
		"paypal_code" => "F6C5V7DTXHXCL",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "outer/stzlifehoodie.black.more.gif",
		"product_image" => "outer/stzlifehoodie.black.products.gif",
		"shirt_color" => "Black",
		"ink_color" => "White",
	),
	
	array(
		"id" => "66",
		"line" => "outer",
		"title" => "STZ Life",
		"basePrice" => "$45",
		"big_image" => "outer/stzlifehoodie.blue.main.gif",
		"paypal_code" => "Y2F8RTRC3V8Y2",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "outer/stzlifehoodie.blue.more.gif",
		"product_image" => "outer/stzlifehoodie.blue.products.gif",
		"shirt_color" => "Blue",
		"ink_color" => "White",
	),
	
	array(
		"id" => "67",
		"line" => "outer",
		"title" => "STZ Life",
		"basePrice" => "$45",
		"big_image" => "outer/stzlifehoodie.grey.main.gif",
		"paypal_code" => "NLQMBVN4WA9QE",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "outer/stzlifehoodie.grey.more.gif",
		"product_image" => "outer/stzlifehoodie.grey.products.gif",
		"shirt_color" => "Grey",
		"ink_color" => "White",
	),
	
	array(
		"id" => "62",
		"line" => "outer",
		"title" => "STZ Life",
		"basePrice" => "$25",
		"big_image" => "outer/stzlifebaseball.grey.main.png",
		"paypal_code" => "4G4T4BZSQLE78",
		"small_description" => "3/4 sleeve raglan baseball tee, 5.4oz, 100% cotton.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "outer/stzlifebaseball.grey.more.png",
		"product_image" => "outer/stzlifebaseball.grey.products.png",
		"shirt_color" => "Grey/Black",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "48",
		"line" => "outer",
		"title" => "STZ Life",
		"basePrice" => "$25",
		"big_image" => "outer/stzlifebaseball.red.main.png",
		"paypal_code" => "S7F3N8LC9ZKH4",
		"small_description" => "3/4 sleeve raglan baseball tee, 5.4oz, 100% cotton.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "outer/stzlifebaseball.red.more.png",
		"product_image" => "outer/stzlifebaseball.red.products.png",
		"shirt_color" => "White/Red",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "46",
		"line" => "outer",
		"title" => "STZ Life",
		"basePrice" => "$25",
		"big_image" => "outer/stzlifebaseball.black.main.png",
		"paypal_code" => "3UW644EAP25X4",
		"small_description" => "3/4 sleeve raglan baseball tee, 5.4oz, 100% cotton.",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "outer/stzlifebaseball.black.more.png",
		"product_image" => "outer/stzlifebaseball.black.products.png",
		"shirt_color" => "White/Black",
		"ink_color" => "Black",
	),	
	
	array(
		"id" => "47",
		"line" => "outer",
		"title" => "Triangle Baseball",
		"basePrice" => "$28",
		"big_image" => "outer/trianglesbaseball.purple.main.png",
		"paypal_code" => "QUP5Z3PS7PBWY",
		"small_description" => "3/4 raglan henley, 38% cotton, 50% poly, 12% rayon. (poly is 6.25% recycled, cotton is 6.25% organic)",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "outer/trianglesbaseball.purple.more.png",
		"product_image" => "outer/trianglesbaseball.purple.products.png",
		"shirt_color" => "Grey/Purple",
		"ink_color" => "Black",
	),
	
		array(
		"id" => "45",
		"line" => "outer",
		"title" => "Triangle Baseball",
		"basePrice" => "$28",
		"big_image" => "outer/trianglesbaseball.red.main.png",
		"paypal_code" => "67NWDMG3WSPGE",
		"small_description" => "3/4 raglan henley, 38% cotton, 50% poly, 12% rayon. (poly is 6.25% recycled, cotton is 6.25% organic)",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "outer/trianglesbaseball.red.more.png",
		"product_image" => "outer/trianglesbaseball.red.products.png",
		"shirt_color" => "Grey/Red",
		"ink_color" => "Black",
	),

	array(
		"id" => "43",
		"line" => "outer",
		"title" => "Triangle Crew",
		"basePrice" => "$40",
		"big_image" => "outer/triangles.crew.main.png",
		"paypal_code" => "3LVN8LQJ29YCQ",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "outer/triangles.crew.more.png",
		"product_image" => "outer/triangles.crew.products.png",
	),
	
	array(
		"id" => "44",
		"line" => "outer",
		"title" => "STZ Life Crew",
		"basePrice" => "$40",
		"big_image" => "outer/stzlife.crew.main.png",
		"paypal_code" => "E6VJJ6KGJ9TVU",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "outer/stzlife.crew.more.png",
		"product_image" => "outer/stzlife.crew.products.png",
	),
	
/********** Hats **********/	
	
	array(
		"id" => "68",
		"line" => "hats",
		"title" => "Aloha",
		"basePrice" => "$35",
		"big_image" => "hats/stzlife.aloha.red.main.gif",
		"paypal_code" => "VCSEJ7A32W46Y",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "hats/stzlife.aloha.red.more.gif",
		"product_image" => "hats/stzlife.aloha.red.products.gif",
	),
	
	array(
		"id" => "69",
		"line" => "hats",
		"title" => "Aloha",
		"basePrice" => "$35",
		"big_image" => "hats/stzlife.aloha.blue.main.gif",
		"paypal_code" => "WVSW9K55B6GYG",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "hats/stzlife.aloha.blue.more.gif",
		"product_image" => "hats/stzlife.aloha.blue.products.gif",
	),
	
	array(
		"id" => "70",
		"line" => "hats",
		"title" => "STZ Life",
		"basePrice" => "$30",
		"big_image" => "hats/stzlife.cord.blue.main.gif",
		"paypal_code" => "456KMXNNL7RSU",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "hats/stzlife.cord.blue.more.gif",
		"product_image" => "hats/stzlife.cord.blue.products.gif",
	),
	
	array(
		"id" => "71",
		"line" => "hats",
		"title" => "STZ Life",
		"basePrice" => "$30",
		"big_image" => "hats/stzlife.cord.green.main.gif",
		"paypal_code" => "R6YJUD7YET6YU",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "hats/stzlife.cord.green.more.gif",
		"product_image" => "hats/stzlife.cord.green.products.gif",
	),
	
	array(
		"id" => "50",
		"line" => "hats",
		"title" => "Logo Snapback",
		"basePrice" => "$25",
		"big_image" => "hats/logo.black.purple.main.png",
		"paypal_code" => "5DULKG5PNC6CY",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "hats/logo.black.purple.more.png",
		"product_image" => "hats/logo.black.purple.products.png",
	),
	
		array(
		"id" => "51",
		"line" => "hats",
		"title" => "Logo Snapback",
		"basePrice" => "$25",
		"big_image" => "hats/logo.maroon.blue.main.png",
		"paypal_code" => "2PACTU6U4PCSG",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "hats/logo.maroon.blue.more.png",
		"product_image" => "hats/logo.maroon.blue.products.png",
	),
	
	array(
		"id" => "52",
		"line" => "hats",
		"title" => "Logo Snapback",
		"basePrice" => "$25",
		"big_image" => "hats/logo.maroon.white.main.png",
		"paypal_code" => "T7ZENZCNQA4YU",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "hats/logo.maroon.white.more.png",
		"product_image" => "hats/logo.maroon.white.products.png",
	),
	
	array(
		"id" => "53",
		"line" => "hats",
		"title" => "Triangle Cord Snapback",
		"basePrice" => "$30",
		"big_image" => "hats/triangle.cord.blue.main.png",
		"paypal_code" => "2G6LGVY85EWDC",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "hats/triangle.cord.blue.more.png",
		"product_image" => "hats/triangle.cord.blue.products.png",
	),
	
		array(
		"id" => "54",
		"line" => "hats",
		"title" => "Triangle Cord Snapback",
		"basePrice" => "$30",
		"big_image" => "hats/triangle.cord.green.main.png",
		"paypal_code" => "ZR3CQR67W5344",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "hats/triangle.cord.green.more.png",
		"product_image" => "hats/triangle.cord.green.products.png",
	),
	/*
	array(
		"id" => "55",
		"line" => "hats",
		"title" => "NC Cord Snapback",
		"basePrice" => "$35",
		"big_image" => "hats/nc.cord.wine.main.png",
		"paypal_code" => "48X7RTN738XJA",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "hats/nc.cord.wine.more.png",
		"product_image" => "hats/nc.cord.wine.products.png",
	),
	*/
	/********* Ladies *********/
	
	array(
		"id" => "60",
		"line" => "ladies",
		"title" => "Triangles Henley",
		"basePrice" => "$28",
		"big_image" => "women/triangles.henley.purple.main.png",
		"paypal_code" => "SHUCL96XJ95QJ",
		"small_description" => "3/4 raglan henley, 38% cotton, 50% poly, 12% rayon. (poly is 6.25% recycled, cotton is 6.25% organic)",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "women/triangles.henley.purple.more.png",
		"product_image" => "women/triangles.henley.purple.products.png",
		"shirt_color" => "Heather Blue",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "56",
		"line" => "ladies",
		"title" => "Triangles Kanga Scoop",
		"basePrice" => "$40",
		"big_image" => "women/triangles.kanga.grey.main.png",
		"paypal_code" => "M876FY2FPH9BG",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "women/triangles.kanga.grey.more.png",
		"product_image" => "women/triangles.kanga.grey.products.png",
		"shirt_color" => "Heather Grey",
		"ink_color" => "Black",
	),
	
		array(
		"id" => "57",
		"line" => "ladies",
		"title" => "Triangles Kanga Scoop",
		"basePrice" => "$40",
		"big_image" => "women/triangles.kanga.purple.main.png",
		"paypal_code" => "UXTP8P4CC42QJ",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "women/triangles.kanga.purple.more.png",
		"product_image" => "women/triangles.kanga.purple.products.png",
		"shirt_color" => "Heather Purple",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "58",
		"line" => "ladies",
		"title" => "Triangles Crew Scoop",
		"basePrice" => "$30",
		"big_image" => "women/triangles.crew.grey.main.png",
		"paypal_code" => "6C8Q378SZ6ECA",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "women/triangles.crew.grey.more.png",
		"product_image" => "women/triangles.crew.grey.products.png",
		"shirt_color" => "Heather Grey",
		"ink_color" => "Black",
	),
	
	array(
		"id" => "59",
		"line" => "ladies",
		"title" => "Triangles Crew Scoop",
		"basePrice" => "$30",
		"big_image" => "women/triangles.crew.blue.main.png",
		"paypal_code" => "5HUXBEVPQSF92",
		"small_description" => "",
		"description" => "",
		"thumbs" => array(
		),
		"more_thumb" => "women/triangles.crew.blue.more.png",
		"product_image" => "women/triangles.crew.blue.products.png",
		"shirt_color" => "Heather Blue",
		"ink_color" => "Black",
	),

);

?>