<?
$design_options = array(
	"Beast Mode" => array(
		"title" => "Beast Mode",
		"normalized" => "beastmode",
		"full_size" => "images/shirtbuilder/graphics/beastmode.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/beastmode.black.thumb.png",
	),
	"Daps n Pounds" => array(
		"title" => "Daps n Pounds",
		"normalized" => "dapsnpounds",
		"full_size" => "images/shirtbuilder/graphics/dapsnpounds.grey.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/dapsnpounds.grey.thumb.png",
	),
	"Double STZ Burger" => array(
		"title" => "Double STZ Burger",
		"normalized" => "doublestzburger",
		"full_size" => "images/shirtbuilder/graphics/doublestzburger.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/doublestzburger.black.thumb.png",
	),
	"El Caputo" => array(
		"title" => "El Caputo",
		"normalized" => "elcaputo",
		"full_size" => "images/shirtbuilder/graphics/elcaputo.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/elcaputo.black.thumb.png",
	),
	"Emergency Mustache" => array(
		"title" => "Emergency Mustache",
		"normalized" => "emergencymustache",
		"full_size" => "images/shirtbuilder/graphics/emergencymustache.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/emergencymustache.black.thumb.png",
	),
	"Gorilla Boombox" => array(
		"title" => "Gorilla Boombox",
		"normalized" => "gorillaboombox",
		"full_size" => "images/shirtbuilder/graphics/gorillaboombox.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/gorillaboombox.black.thumb.png",
	),
	"Skyline" => array(
		"title" => "Skyline",
		"normalized" => "skyline",
		"full_size" => "images/shirtbuilder/graphics/skyline.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/skyline.black.thumb.png",
	),
	"I Skate NC" => array(
		"title" => "I Skate NC",
		"normalized" => "iskatenc",
		"full_size" => "images/shirtbuilder/graphics/iskatenc.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/iskatenc.black.thumb.png",
	),
	"I Skate NC" => array(
		"title" => "I Skate NC (Blue)",
		"normalized" => "iskatencblue",
		"full_size" => "images/shirtbuilder/graphics/iskatenc.blue.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/iskatenc.blue.thumb.png",
	),
	"Moostache" => array(
		"title" => "Moostache",
		"normalized" => "moostache",
		"full_size" => "images/shirtbuilder/graphics/moostache.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/moostache.black.thumb.png",
	),
	"Party Animals" => array(
		"title" => "Party Animals",
		"normalized" => "partyanimals",
		"full_size" => "images/shirtbuilder/graphics/partyanimals.grey.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/partyanimals.grey.thumb.png",
	),
	"Peace" => array(
		"title" => "Peace (Black)",
		"normalized" => "peaceblack",
		"full_size" => "images/shirtbuilder/graphics/peace.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/peace.black.thumb.png",
	),
	"Peace" => array(
		"title" => "Peace (Blue)",
		"normalized" => "peaceblue",
		"full_size" => "images/shirtbuilder/graphics/peace.blue.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/peace.blue.thumb.png",
	),
	"Ride NC Black" => array(
		"title" => "Ride NC (Black)",
		"normalized" => "ridencblack",
		"full_size" => "images/shirtbuilder/graphics/ridenc.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/ridenc.black.thumb.png",
	),
	"Ride NC Orange" => array(
		"title" => "Ride NC (Orange)",
		"normalized" => "ridencorange",
		"full_size" => "images/shirtbuilder/graphics/ridenc.orange.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/ridenc.orange.thumb.png",
	),
	"Right Coast" => array(
		"title" => "Right Coast",
		"normalized" => "rightcoast",
		"full_size" => "images/shirtbuilder/graphics/rightcoast.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/rightcoast.black.thumb.png",
	),
	"Shoot All Shred" => array(
		"title" => "Shoot All Shred",
		"normalized" => "shootallshred",
		"full_size" => "images/shirtbuilder/graphics/shootallshred.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/shootallshred.black.thumb.png",
	),
	"Shred Til You're Dead" => array(
		"title" => "Shred Til You're Dead",
		"normalized" => "shredtilyouredead",
		"full_size" => "images/shirtbuilder/graphics/shredtilyouredead.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/shredtilyouredead.black.thumb.png",
	),
	"Triangles" => array(
		"title" => "Triangles",
		"normalized" => "triangles",
		"full_size" => "images/shirtbuilder/graphics/triangles.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/triangles.black.thumb.png",
	),
	"Hand Shredded" => array(
		"title" => "Hand Shredded",
		"normalized" => "handshredded",
		"full_size" => "images/shirtbuilder/graphics/handshredded.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/handshredded.black.thumb.png",
	),
	"We Can Do It" => array(
		"title" => "We Can Do It",
		"normalized" => "wecandoit",
		"full_size" => "images/shirtbuilder/graphics/wecandoit.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/wecandoit.black.thumb.png",
	),
	"Happy Shredding" => array(
		"title" => "Happy Shredding",
		"normalized" => "happyshredding",
		"full_size" => "images/shirtbuilder/graphics/happyshredding.orange.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/happyshredding.orange.thumb.png",
	),
	"KJ Gorilla" => array(
		"title" => "KJ Gorilla",
		"normalized" => "kjgorilla",
		"full_size" => "images/shirtbuilder/graphics/kjgorilla.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/kjgorilla.black.thumb.png",
	),
	"OG Whaler Black" => array(
		"title" => "OG Whaler (Black)",
		"normalized" => "ogwhalerblack",
		"full_size" => "images/shirtbuilder/graphics/ogwhaler.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/ogwhaler.black.thumb.png",
	),
	"OG Whaler White" => array(
		"title" => "OG Whaler (White)",
		"normalized" => "ogwhalerwhite",
		"full_size" => "images/shirtbuilder/graphics/ogwhaler.white.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/ogwhaler.white.thumb.png",
	),
	"Slush Buddie" => array(
		"title" => "Slush Buddie (White)",
		"normalized" => "slushbuddie",
		"full_size" => "images/shirtbuilder/graphics/slushbuddie.white.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/slushbuddie.white.thumb.png",
	),
	"STZ Life" => array(
		"title" => "STZ Life",
		"normalized" => "stzlife",
		"full_size" => "images/shirtbuilder/graphics/stzlife.black.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/stzlife.black.thumb.png",
	),
	"Too Fresh" => array(
		"title" => "Too Fresh",
		"normalized" => "toofresh",
		"full_size" => "images/shirtbuilder/graphics/toofresh.blue.png",
		"thumb" => "images/shirtbuilder/graphicthumbs/toofresh.blue.thumb.png",
	),
);
?>